"""feat: разрешить конфликты DOI публикаций

Revision ID: b7845acab1a8
Revises: c4811c2fcceb
Create Date: 2026-08-20 11:41:35.079515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7845acab1a8'
down_revision = 'c4811c2fcceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('publications_doi_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('publications_doi_key'), ['doi'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
